name: Robin
favicon: null
layout_spectrum: 1
typography_spectrum: 0.07867
title: Adventures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-78245807-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
